/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 isuzu3.glb -t -K 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    axel_back: THREE.Mesh
    axel_front: THREE.Mesh
    axel_holder_back: THREE.Mesh
    axel_holder_front: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11001: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    wheel_back: THREE.Mesh
    pich_back: THREE.Mesh
    wheel_inside2_back: THREE.Mesh
    wheel_inside_back: THREE.Mesh
    wheel_inside2_front: THREE.Mesh
    pich_front: THREE.Mesh
    wheel_fron_inside: THREE.Mesh
    wheel_front_left: THREE.Mesh
    wheel_front_right: THREE.Mesh
    z_body_main001: THREE.Mesh
    z_body_lights: THREE.Mesh
    z_body_lights001: THREE.Mesh
    z_body_main003: THREE.Mesh
    z_body_main004: THREE.Mesh
    z_body_top: THREE.Mesh
    z_step004: THREE.Mesh
    z_body_top001: THREE.Mesh
  }
  materials: {
    mat_2: THREE.MeshStandardMaterial
    object_16: THREE.MeshStandardMaterial
    object_17: THREE.MeshStandardMaterial
    object_18: THREE.MeshStandardMaterial
    object_2: THREE.MeshStandardMaterial
    object_8: THREE.MeshStandardMaterial
    mat_1: THREE.MeshStandardMaterial
    mat_3: THREE.MeshStandardMaterial
    object_0: THREE.MeshStandardMaterial
    object_11: THREE.MeshStandardMaterial
    object_13: THREE.MeshStandardMaterial
    object_14: THREE.MeshStandardMaterial
    object_15: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Color_003: THREE.MeshStandardMaterial
    ['Brushed used metal silver']: THREE.MeshStandardMaterial
    ['Blue matte metal']: THREE.MeshStandardMaterial
    ['mat_2.001']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/isuzu3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <group>
          <group>
            <group />
            <mesh geometry={nodes.axel_back.geometry} material={materials.mat_2} />
            <mesh geometry={nodes.axel_front.geometry} material={materials.mat_2} />
            <mesh geometry={nodes.axel_holder_back.geometry} material={materials.mat_2} />
            <mesh geometry={nodes.axel_holder_front.geometry} material={materials.mat_2} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.object_16} />
            <mesh geometry={nodes.Object_11001.geometry} material={materials.object_17} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.object_18} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.object_2} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.object_8} />
            <mesh geometry={nodes.Object_2.geometry} material={materials.mat_1} />
            <mesh geometry={nodes.Object_3.geometry} material={materials.mat_2} />
            <mesh geometry={nodes.Object_4.geometry} material={materials.mat_3} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.object_0} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.object_11} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.object_13} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.object_14} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.object_15} />
            <mesh geometry={nodes.wheel_back.geometry} material={materials.object_16}>
              <mesh geometry={nodes.pich_back.geometry} material={materials.object_18} />
              <mesh geometry={nodes.wheel_inside2_back.geometry} material={materials.mat_2} />
              <mesh geometry={nodes.wheel_inside_back.geometry} material={materials.object_17} />
            </mesh>
            <mesh geometry={nodes.wheel_inside2_front.geometry} material={materials.mat_2}>
              <mesh geometry={nodes.pich_front.geometry} material={materials.object_18} />
              <mesh geometry={nodes.wheel_fron_inside.geometry} material={materials.object_17} />
              <mesh geometry={nodes.wheel_front_left.geometry} material={materials.object_16} />
              <mesh geometry={nodes.wheel_front_right.geometry} material={materials.object_16} />
            </mesh>
          </group>
        </group>
        <group>
          <group>
            <mesh geometry={nodes.z_body_main001.geometry} material={materials.mat_2}>
              <group />
              <group />
              <group />
              <mesh geometry={nodes.z_body_lights.geometry} material={materials.material} />
              <mesh geometry={nodes.z_body_lights001.geometry} material={materials.Color_003} />
              <mesh geometry={nodes.z_body_main003.geometry} material={materials['Brushed used metal silver']} />
              <mesh geometry={nodes.z_body_main004.geometry} material={materials['Blue matte metal']} />
              <mesh geometry={nodes.z_body_top.geometry} material={materials.mat_2} />
              <mesh geometry={nodes.z_step004.geometry} material={materials['mat_2.001']} />
            </mesh>
          </group>
        </group>
        <mesh geometry={nodes.z_body_top001.geometry} material={materials['mat_2.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/isuzu3.glb')
