/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 isuzu_giga_dump_truck.glb -t 
Author: wolfoo motors (https://sketchfab.com/mariteslara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isuzu-giga-dump-truck-3349f2616d0345f49cda7e8fa5619d80
Title: isuzu giga dump truck
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Material2: THREE.Mesh
    Material4: THREE.Mesh
    Material4_1: THREE.Mesh
    Material5: THREE.Mesh
    Material5_1: THREE.Mesh
    Material6: THREE.Mesh
    Material6_1: THREE.Mesh
    Material6_2: THREE.Mesh
    Material8: THREE.Mesh
    Material8_1: THREE.Mesh
    Material8_2: THREE.Mesh
    Material4_2: THREE.Mesh
    Material2_1: THREE.Mesh
    Material2_2: THREE.Mesh
    Material3: THREE.Mesh
    Material3_1: THREE.Mesh
    Material2_3: THREE.Mesh
    Material2_4: THREE.Mesh
    Material3_2: THREE.Mesh
    Material3_3: THREE.Mesh
    Material3_4: THREE.Mesh
    Material3_5: THREE.Mesh
    Material2_5: THREE.Mesh
    Material2_6: THREE.Mesh
    Material3_6: THREE.Mesh
    Material3_7: THREE.Mesh
    Material3_8: THREE.Mesh
    Material2_7: THREE.Mesh
    Material2_9: THREE.Mesh
    Material2_10: THREE.Mesh
    Material2_11: THREE.Mesh
    Material4_3: THREE.Mesh
    Material2_12: THREE.Mesh
    Material2_13: THREE.Mesh
    Material2_14: THREE.Mesh
    Material2_15: THREE.Mesh
    Material3_9: THREE.Mesh
    Material3_10: THREE.Mesh
    Material3_11: THREE.Mesh
    Material2_8: THREE.Mesh
    Material3_12: THREE.Mesh
  }
  materials: {
    Charcoal: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    Color_005: THREE.MeshStandardMaterial
    Gray6: THREE.MeshStandardMaterial
    edge_color114114114255: THREE.LineBasicMaterial
    Color_000: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    Color_003: THREE.MeshStandardMaterial
    Color_A07: THREE.MeshStandardMaterial
    Color_D02: THREE.MeshStandardMaterial
    edge_color142142142255: THREE.LineBasicMaterial
    Color_004: THREE.MeshStandardMaterial
    edge_color204204122255: THREE.LineBasicMaterial
    edge_color12710224255: THREE.LineBasicMaterial
    edge_color868686255: THREE.LineBasicMaterial
    Color_006: THREE.MeshStandardMaterial
    Color_G20: THREE.MeshStandardMaterial
    edge_color303030255: THREE.LineBasicMaterial
    Color_000_1: THREE.MeshStandardMaterial
    edge_color969696255: THREE.LineBasicMaterial
    Color_000_2: THREE.MeshStandardMaterial
    Translucent_Glass_Gray: THREE.MeshStandardMaterial
    edge_color100149237255: THREE.LineBasicMaterial
    Color_C03: THREE.MeshStandardMaterial
    Color_007: THREE.MeshStandardMaterial
    edge_color176896255: THREE.LineBasicMaterial
    Color_H14: THREE.MeshStandardMaterial
    edge_color255255255255: THREE.LineBasicMaterial
    Color_008: THREE.MeshStandardMaterial
    Color_009: THREE.MeshStandardMaterial
    edge_color247255249255: THREE.LineBasicMaterial
    edge_color353535255: THREE.LineBasicMaterial
    edge_color000255: THREE.LineBasicMaterial
    edge_color170170170255: THREE.LineBasicMaterial
    edge_color251255248255: THREE.LineBasicMaterial
    edge_color585858255: THREE.LineBasicMaterial
    edge_color235242237255: THREE.LineBasicMaterial
  }
  // animations: GLTFAction[]
}

export function IsuzuTruck(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/isuzu_giga_dump_truck.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={0.02}>
      <group >
        <mesh geometry={nodes.Material2.geometry} material={materials.Charcoal} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Material3.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.Gray6} />
        <lineSegments geometry={nodes.Material2_10.geometry} material={materials.edge_color353535255} />
        <lineSegments geometry={nodes.Material2_11.geometry} material={materials.edge_color000255} />
        <lineSegments geometry={nodes.Material2_12.geometry} material={materials.edge_color170170170255} />
        {/* <lineSegments geometry={nodes.Material4_3.geometry} material={materials.edge_color000255} /> */}

      </group>
        <lineSegments geometry={nodes.Material5.geometry} material={materials.edge_color114114114255} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Material3_3.geometry} material={materials.Color_003} />
        <mesh geometry={nodes.Material3_4.geometry} material={materials.Color_A07} />
        <mesh geometry={nodes.Material3_5.geometry} material={materials.Color_D02} />
        <lineSegments geometry={nodes.Material4.geometry} material={materials.edge_color142142142255} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_004} />
        <lineSegments geometry={nodes.Material6.geometry} material={materials.edge_color204204122255} />
        <lineSegments geometry={nodes.Material8.geometry} material={materials.edge_color12710224255} />
        <lineSegments geometry={nodes.Material4_1.geometry} material={materials.edge_color868686255} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Color_006} />
        <mesh geometry={nodes.Material3_6.geometry} material={materials.Color_G20} />
        <lineSegments geometry={nodes.Material6_1.geometry} material={materials.edge_color303030255} />
        <mesh geometry={nodes.Material3_7.geometry} material={materials.Color_000_1} />
        <lineSegments geometry={nodes.Material8_1.geometry} material={materials.edge_color969696255} />
        <mesh geometry={nodes.Material3_8.geometry} material={materials.Color_000_2} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.Translucent_Glass_Gray} />
        <lineSegments geometry={nodes.Material5_1.geometry} material={materials.edge_color100149237255} />
        <mesh geometry={nodes.Material3_9.geometry} material={materials.Color_C03} />
        <mesh geometry={nodes.Material3_10.geometry} material={materials.Color_007} />
        <lineSegments geometry={nodes.Material4_2.geometry} material={materials.edge_color176896255} />
        <mesh geometry={nodes.Material3_11.geometry} material={materials.Color_H14} />
        <lineSegments geometry={nodes.Material6_2.geometry} material={materials.edge_color255255255255} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material3_12.geometry} material={materials.Color_009} />
        <lineSegments geometry={nodes.Material2_9.geometry} material={materials.edge_color247255249255} />
        <lineSegments geometry={nodes.Material2_13.geometry} material={materials.edge_color251255248255} />
        <lineSegments geometry={nodes.Material2_14.geometry} material={materials.edge_color585858255} />
        <lineSegments geometry={nodes.Material2_15.geometry} material={materials.edge_color235242237255} />
      </group>
    </group>
  )
}

useGLTF.preload('/isuzu_giga_dump_truck.glb')
